apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  type: NodePort
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000   # 👈 must match containerPort
      nodePort: 30007    # accessible at localhost:30007
